# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-12 15:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('freelance', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('surname', models.CharField(max_length=100, verbose_name='Фамилия')),
                ('name', models.CharField(max_length=50, verbose_name='Имя')),
                ('types', models.CharField(max_length=250, verbose_name='Обл. деятельности')),
                ('telephone', models.CharField(max_length=20, verbose_name='Телефон')),
                ('description', models.TextField(verbose_name='Описание')),
                ('price_start', models.IntegerField(default=0, verbose_name='Начальная цена')),
                ('price_end', models.IntegerField(default=0, verbose_name='Конечная цена')),
                ('date_time', models.CharField(default='Не важно', max_length=100, verbose_name='Дата и время')),
            ],
            options={
                'db_table': 'Orders',
                'verbose_name': 'Заказы',
            },
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название')),
            ],
        ),
        migrations.AddField(
            model_name='orders',
            name='region',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='freelance.Region', verbose_name='Регион'),
        ),
        migrations.AddField(
            model_name='orders',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='freelance.Work', verbose_name='Категория'),
        ),
    ]
