# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-12 15:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('freelance', '0002_auto_20170512_1859'),
    ]

    operations = [
        migrations.CreateModel(
            name='Workers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('surname', models.CharField(max_length=100, verbose_name='Фамилия')),
                ('name', models.CharField(max_length=50, verbose_name='Имя')),
                ('email', models.EmailField(max_length=254, verbose_name='E-mail')),
                ('telephone', models.CharField(max_length=20, verbose_name='Телефон')),
                ('SNILS', models.IntegerField(verbose_name='СНИЛС')),
                ('password', models.CharField(max_length=100, verbose_name='Пароль')),
                ('type', models.CharField(max_length=250, verbose_name='Обл. деятельности')),
                ('region', models.CharField(max_length=100, verbose_name='Регион')),
            ],
            options={
                'verbose_name': 'Соискатели',
                'db_table': 'Workers',
            },
        ),
    ]
