# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-12 16:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('freelance', '0005_workers_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workers',
            name='SNILS',
            field=models.IntegerField(max_length=11, verbose_name='СНИЛС'),
        ),
        migrations.RemoveField(
            model_name='workers',
            name='region',
        ),
        migrations.AddField(
            model_name='workers',
            name='region',
            field=models.ManyToManyField(to='freelance.Region', verbose_name='Регион'),
        ),
    ]
