# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-12 16:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('freelance', '0006_auto_20170512_1943'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workers',
            name='category',
        ),
        migrations.RemoveField(
            model_name='workers',
            name='type',
        ),
        migrations.AddField(
            model_name='workers',
            name='type',
            field=models.ManyToManyField(to='freelance.Work'),
        ),
    ]
