# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-12 16:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('freelance', '0007_auto_20170512_1953'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workers',
            name='SNILS',
            field=models.IntegerField(verbose_name='СНИЛС'),
        ),
    ]
