# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-12 18:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('freelance', '0008_auto_20170512_1953'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='work',
            name='type',
        ),
        migrations.DeleteModel(
            name='Type_of_Work',
        ),
    ]
