# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-13 09:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('freelance', '0011_auto_20170513_1249'),
    ]

    operations = [
        migrations.AddField(
            model_name='workers',
            name='region',
            field=models.ManyToManyField(to='freelance.Region', verbose_name='Регион'),
        ),
        migrations.AddField(
            model_name='workers',
            name='type',
            field=models.ManyToManyField(to='freelance.Work'),
        ),
    ]
