# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-13 10:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('freelance', '0013_auto_20170513_1313'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Workers',
        ),
    ]
