# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-13 10:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('freelance', '0016_auto_20170513_1323'),
    ]

    operations = [
        migrations.AddField(
            model_name='workers',
            name='region',
            field=models.CharField(default=None, max_length=10),
        ),
        migrations.AddField(
            model_name='workers',
            name='type',
            field=models.CharField(default=None, max_length=10),
        ),
    ]
