# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-13 10:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('freelance', '0017_auto_20170513_1324'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workers',
            name='region',
        ),
        migrations.AddField(
            model_name='workers',
            name='region',
            field=models.ManyToManyField(to='freelance.Region', verbose_name='Регион'),
        ),
    ]
