# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-13 10:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('freelance', '0019_auto_20170513_1326'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='mailed',
            field=models.BooleanField(default=False),
        ),
    ]
