# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-13 11:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('freelance', '0020_orders_mailed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='mailed',
            field=models.NullBooleanField(),
        ),
    ]
