# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-18 12:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('freelance', '0023_auto_20170513_1404'),
    ]

    operations = [
        migrations.CreateModel(
            name='Link_Section',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='Навание вида работы:')),
                ('image', models.ImageField(upload_to='', verbose_name='Изображение')),
                ('link', models.CharField(max_length=120, verbose_name='Ссылка')),
            ],
        ),
    ]
