# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-28 10:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('freelance', '0025_auto_20170528_1254'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Uteplenie',
            new_name='Pokraska',
        ),
        migrations.AlterModelOptions(
            name='pokraska',
            options={'verbose_name': 'Побелить покрасить'},
        ),
    ]
