# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-28 10:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('freelance', '0027_auto_20170528_1310'),
    ]

    operations = [
        migrations.AddField(
            model_name='pokraska',
            name='mailed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='pokraska',
            name='message',
            field=models.TextField(default=None),
        ),
    ]
