# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-28 11:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('freelance', '0028_auto_20170528_1344'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='pokraska',
            table='pokraska',
        ),
    ]
