# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-28 11:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('freelance', '0029_auto_20170528_1417'),
    ]

    operations = [
        migrations.CreateModel(
            name='Uteplenie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ploshad', models.CharField(max_length=25)),
                ('material', models.CharField(max_length=100)),
                ('otkosi', models.CharField(max_length=100)),
                ('finish', models.CharField(max_length=20)),
                ('finish_material', models.CharField(max_length=20)),
                ('material_ot', models.CharField(max_length=20)),
                ('details', models.TextField()),
                ('money', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=20)),
                ('district', models.CharField(max_length=20)),
                ('phone', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254)),
                ('message', models.TextField(default=None)),
                ('mailed', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Утепление',
                'db_table': 'uteplenie',
            },
        ),
    ]
