# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-28 12:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('freelance', '0030_uteplenie'),
    ]

    operations = [
        migrations.CreateModel(
            name='Design',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_type', models.CharField(max_length=30)),
                ('what_do', models.CharField(default='Не определено.', max_length=50)),
                ('details', models.TextField()),
                ('money', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=20)),
                ('district', models.CharField(max_length=20)),
                ('phone', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254)),
                ('message', models.TextField(default=None)),
                ('mailed', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Дизайн интерьер/проект',
                'db_table': 'design',
            },
        ),
        migrations.AddField(
            model_name='pokraska',
            name='potolki',
            field=models.CharField(default='не требуется', max_length=20),
        ),
    ]
