# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-29 10:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('freelance', '0034_redecorating'),
    ]

    operations = [
        migrations.CreateModel(
            name='Plitka',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ploshad', models.CharField(max_length=20)),
                ('santehnika', models.CharField(max_length=10)),
                ('material_ot', models.CharField(max_length=15)),
                ('details', models.TextField()),
                ('money', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=20)),
                ('district', models.CharField(max_length=20)),
                ('phone', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('message', models.TextField(default=None)),
                ('mailed', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Плитка',
                'db_table': 'plitka',
            },
        ),
        migrations.AlterField(
            model_name='design',
            name='phone',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='osteklenie_balkonov',
            name='phone',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='otoplenie',
            name='phone',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='pokraska',
            name='phone',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='redecorating',
            name='phone',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='uteplenie',
            name='phone',
            field=models.CharField(max_length=20),
        ),
    ]
