# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-29 10:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('freelance', '0035_auto_20170529_1324'),
    ]

    operations = [
        migrations.CreateModel(
            name='Krovlya',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ploshad', models.CharField(max_length=20)),
                ('postavka_materiala', models.CharField(max_length=10)),
                ('dop', models.CharField(max_length=50)),
                ('details', models.TextField()),
                ('money', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=20)),
                ('district', models.CharField(max_length=20)),
                ('phone', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('message', models.TextField(default=None)),
                ('mailed', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Кровля',
                'db_table': 'krovlya',
            },
        ),
    ]
