# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-29 12:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('freelance', '0037_poli'),
    ]

    operations = [
        migrations.CreateModel(
            name='Raboti_pod_kluch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ploshad', models.CharField(max_length=20)),
                ('room_type', models.CharField(max_length=20)),
                ('works', models.TextField()),
                ('details', models.TextField()),
                ('money', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=20)),
                ('district', models.CharField(max_length=20)),
                ('phone', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('message', models.TextField(default=None)),
                ('mailed', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Работы под ключ',
                'db_table': 'raboti_pod_kluch',
            },
        ),
        migrations.AddField(
            model_name='poli',
            name='materiali_ot',
            field=models.CharField(default='заказчик', max_length=20),
        ),
    ]
