# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-30 12:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('freelance', '0039_santehnika'),
    ]

    operations = [
        migrations.CreateModel(
            name='Potolki',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ploshad', models.CharField(max_length=20)),
                ('material', models.CharField(max_length=20)),
                ('isol', models.CharField(max_length=200)),
                ('svet', models.CharField(max_length=20)),
                ('details', models.TextField()),
                ('money', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=20)),
                ('district', models.CharField(max_length=20)),
                ('phone', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('message', models.TextField(default=None)),
                ('mailed', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Потолки',
                'db_table': 'potolki',
            },
        ),
    ]
