# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-06-04 11:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('freelance', '0041_gipsokarton_peregorodki'),
    ]

    operations = [
        migrations.CreateModel(
            name='Remont_vannoy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ploshad', models.CharField(max_length=20)),
                ('plitka', models.CharField(max_length=20)),
                ('santehika', models.CharField(max_length=20)),
                ('details', models.TextField()),
                ('money', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=20)),
                ('district', models.CharField(max_length=20)),
                ('phone', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('message', models.TextField(default=None)),
                ('mailed', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'Remont_vannoy',
                'verbose_name': 'Ремонт ванной',
            },
        ),
    ]
