# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-06-05 14:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('freelance', '0042_remont_vannoy'),
    ]

    operations = [
        migrations.CreateModel(
            name='Beton',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ploshad', models.CharField(max_length=20)),
                ('details', models.TextField()),
                ('money', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=20)),
                ('district', models.CharField(max_length=20)),
                ('phone', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('message', models.TextField(default=None)),
                ('mailed', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'Beton',
                'verbose_name': 'Бетонные работы',
            },
        ),
        migrations.CreateModel(
            name='Natyazhnoi_potolok',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ploshad', models.CharField(max_length=20)),
                ('svet', models.CharField(max_length=20)),
                ('details', models.TextField()),
                ('money', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=20)),
                ('district', models.CharField(max_length=20)),
                ('phone', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('message', models.TextField(default=None)),
                ('mailed', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'Natyazhnoi_potolok',
                'verbose_name': 'Наятяжной потолок',
            },
        ),
        migrations.CreateModel(
            name='Oboi',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ploshad', models.CharField(max_length=20)),
                ('details', models.TextField()),
                ('money', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=20)),
                ('district', models.CharField(max_length=20)),
                ('phone', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('message', models.TextField(default=None)),
                ('mailed', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'Oboi',
                'verbose_name': 'Поклейка обоев',
            },
        ),
        migrations.CreateModel(
            name='Reshetki',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.CharField(max_length=20)),
                ('type', models.CharField(max_length=20)),
                ('details', models.TextField()),
                ('money', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=20)),
                ('district', models.CharField(max_length=20)),
                ('phone', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('message', models.TextField(default=None)),
                ('mailed', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'Reshetki',
                'verbose_name': 'Решетки',
            },
        ),
    ]
