# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-06-08 12:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('freelance', '0043_beton_natyazhnoi_potolok_oboi_reshetki'),
    ]

    operations = [
        migrations.DeleteModel(
            name='City',
        ),
        migrations.DeleteModel(
            name='User_DATA',
        ),
        migrations.RemoveField(
            model_name='workers',
            name='region',
        ),
        migrations.AddField(
            model_name='workers',
            name='region',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.RemoveField(
            model_name='workers',
            name='type',
        ),
        migrations.AddField(
            model_name='workers',
            name='type',
            field=models.TextField(default=''),
        ),
        migrations.DeleteModel(
            name='Region',
        ),
    ]
