# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-06-08 12:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('freelance', '0044_auto_20170608_1504'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Workers',
        ),
    ]
